import Lake
open Lake DSL

package «navier-stokes» where
  -- name field omitted: Lake infers it from the package identifier above

require mathlib from git
  "https://github.com/leanprover-community/mathlib4.git" @ "v4.12.0"

lean_lib Towers where
  roots := #[`Towers.NS.EnergyIneq,
             `Towers.NS.EnergyV2,
             `Towers.NS.Divergence,
             `Towers.NS.Wall300_Scaffold,
             `Towers.NS.NSStokesAdjoint,
             `Towers.NS.NSNonlinearTerm,
             `Towers.NS.NSClayCombinator,
             `Towers.NS.NSAubinLionsDecomp,
             `Towers.NS.NSCanonicalSurfaces,
             `Towers.NS.NSGate2Decomp,
             `Towers.NS.NSGate3Decomp,
             `Towers.NS.NSKPBridge,
             `Towers.NS.NSLittlewoodPaley,
             `Towers.NS.NSLPKPCertificate,
             `Towers.NS.NSCollection,
             `Towers.NS.NSStokesSmoothing,
             `Towers.NS.NSSemigroupDef,
             `Towers.NS.NSCorrSemigroupSmooth,
             `Towers.NS.NSOrbitClosure,
             `Towers.NS.NSGeneratorClose,
             `Towers.NS.NSFourierInner,
             `Towers.NS.NSMuIntegralShift,
             `Towers.NS.NSParametricDiff,
             `Towers.NS.NSBochnerDiff,
             `Towers.NS.NSDerivSemigroup,
             `Towers.NS.NSLpErrorPlumbing,
             `Towers.NS.NSStokesMaxReg,
             `Towers.NS.NSAdjointArgument,
             `Towers.NS.NSAdjointPackageClose,
             `Towers.NS.NSAdjointPackagePartBClose,
             `Towers.NS.NSWeakInitContClose,
             `Towers.NS.NSCorrSemigroupContinuity,
             `Towers.NS.NSCorrSemigroupLipAtZero,
             `Towers.NS.NSWeakInitContOrbit,
             `Towers.NS.NSWeakMomentumDiffAtClose,
             `Towers.NS.NSAdjointIntegralClose,
             `Towers.NS.NSCorrSemigroupSelfAdj,
             `Towers.NS.NSWeakInitContDirect,
             `Towers.NS.NSWeakMomentumDiffAtProved,
             `Towers.NS.NSAdjointSymmetry,
             `Towers.NS.NSScalarLeibnizAdjoint,
             `Towers.NS.NSPhase40AdjClose,
             `Towers.NS.NSPhase41ThreeGaps,
             `Towers.NS.NSPhase42ZeroForcing,
             `Towers.NS.NSPhase43ForcingOrbitZero,
             `Towers.NS.NSPhase44ExpIntegral,
             `Towers.NS.NSPhase45WeakForcingIsZero,
             `Towers.NS.NSPhase46StokesMaxReg,
             `Towers.NS.NSPhase52D5MasterBridge,
             `Towers.NS.NSPhase53GapClosure,
             `Towers.NS.NSPhase56D1Decomposition,
             `Towers.NS.NSPhase57PeetreDecomp,
             `Towers.NS.NSPhase58YoungDecomp,
             `Towers.NS.NSPhase59D1Closure,
             `Towers.NS.NSPhase60SobolevLInf,
             `Towers.NS.NSPhase61HLSStructure,
             `Towers.NS.NSPhase62RieszGeometry,
             `Towers.NS.NSPhase63Marcinkiewicz,
             `Towers.NS.NSPhase64FourierBridge,
             `Towers.NS.NSPhase65VolumeClosure,
             `Towers.NS.NSPhase66VolumeProof,
             `Towers.NS.NSPhase67YoungGap,
             `Towers.NS.NSPhase68YoungConditional,
             `Towers.NS.NSPhase69HLSGap,
             `Towers.NS.NSPhase70YoungClosure,
             `Towers.NS.NSPhase71PlancherelClosure,
             `Towers.NS.NSPhase72FourierChain,
             `Towers.NS.NSPhase73FourierSubgaps,
             `Towers.NS.NSPhase74FourierAudit,
             `Towers.NS.NSPhase75ExponentCorrection,
             `Towers.NS.NSClayCertificateV2]
